
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge